---
# ahuffman.resolv: https://github.com/ahuffman/ansible-resolv
#  - installed via ansible-galaxy install -r requirements.yaml
- name: configure a computer in mikes house
  become: yes
  tasks:
    - name: upgrade apt packages
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: install apt packages
      apt:
        update_cache: yes
        cache_valid_time: 3600
        state: present
        name:
          - smbclient
          - cifs-utils

    - name: configure DNS
      include_role:
        name: ahuffman.resolv
        vars:
          resolv_nameservers:
            # points at google fiber router
            - 192.168.1.1
    
    - name: setup smb credentials
      include_vars: defaults/smb.yml
      template:
        src: smb.j2
        dest: /etc/samba/credentials
