---
# apt action: https://docs.ansible.com/ansible/latest/modules/apt_module.html
# pip action: https://docs.ansible.com/ansible/latest/modules/pip_module.html
- name: configure an erisyon dev server
  become: yes
  tasks:
  - name: upgrade installed packages
    apt:
      upgrade: yes

  - name: install apt packages
    apt:
      update_cache: yes
      cache_valid_time: 3600
      state: present
      name:  
        - docker.io
        - python3
        - python3-pip
  
  - name: install pip packages
    pip:
      name:
          - awscli
