---
- name: upgrade installed packages
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: "yes"

# necessary for us to run >5.7 kernel for Photometrics Cameras
- name: add kernal PPA for updated kernel
  ansible.builtin.apt_repository:
    repo: ppa:cappelikan/ppa

# add key for nodesource repo
- name: add apt key for nodesource repo
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

# add node source repo
- name: add nodesource repo
  ansible.builtin.apt_repository:
    repo: deb https://deb.nodesource.com/node_14.x focal main
    filename: yarn

# add key for yarn repo
- name: add apt key for yarn repo
  ansible.builtin.apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

# add yarn repo
- name: add yarn repo
  ansible.builtin.apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    filename: yarn

# add key for kubectl repo
- name: add apt key for kubectl repo
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

# add kubectl repo
- name: add yarn repo
  ansible.builtin.apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    filename: kubectl

# add packagecloud gpg key; needed for git-lfs
- name: add packagecloud gpg
  ansible.builtin.apt_key:
    url: https://packagecloud.io/github/git-lfs/gpgkey

# packagecloud repo with gitlfs in it
- name: add packagecloud repo
  ansible.builtin.apt_repository:
    repo: deb https://packagecloud.io/github/git-lfs/ubuntu/ focal main
    filename: packagecloud

- name: install apt packages
  ansible.builtin.apt:
    state: present
    update_cache: yes
    cache_valid_time: 3600
    name:
      # updated kernel
      - linux-headers-5.8.0-48-generic
      - linux-image-5.8.0-48-generic
      - linux-modules-5.8.0-48-generic
      # things like kernel module for usbserial (not included in our cloudimg)
      - linux-modules-extra-5.8.0-48-generic
      # general
      - curl
      - nfs-common
      - ntp
      - python3
      - python3-pip
      - git
      - git-lfs
      # for docker commmunity edition
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      # for pyenv / python installations
      - build-essential
      - libbz2-dev
      - libffi-dev
      - liblzma-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - llvm
      - make
      - python-openssl
      - tk-dev
      - xz-utils
      - zlib1g-dev
      # for vega dev
      - nodejs
      - yarn
      - ffmpeg
      # dev general
      - watchman
      # erisyon/internal dev
      - kubectl

- name: remove snapd
  ansible.builtin.apt:
    state: absent
    purge: yes
    name:
      - snapd

- name: setup docker apt key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: setup docker community edition repo
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: install docker community edition package
  ansible.builtin.apt:
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: copy resolv.conf
  ansible.builtin.copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: "0644"
  register: resolvconf

- name: restart systemd-resolvd
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
  when: resolvconf.changed

