---
- name: install common packages
  ansible.builtin.apt:
    state: present
    update_cache: yes
    cache_valid_time: 3600
    name:
      - curl
      - python3
      - python3-pip
      - git
      - ntp

- name: remove snapd
  ansible.builtin.apt:
    state: absent
    purge: yes
    name:
      - snapd

