---
- name: grant sudoers sudoer without pw
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^%sudo +ALL='
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s

