---
- name: common packages
  ansible.builtin.import_tasks: common/packages.yml

- name: setup sudo permissions
  ansible.builtin.import_tasks: common/sudo.yml

- name: setup secure ssh
  ansible.builtin.import_tasks: common/ssh.yml
