---
- name: install common packages
  become: yes
  ansible.builtin.apt:
    state: present
    update_cache: yes
    cache_valid_time: 3600
    name:
      - curl
      - python3
      - python3-pip
      - git

- name: grant sudoers sudoer without pw
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^%sudo +ALL='
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s

- name: sshd local bind unlike; removes forwarded sockets on d/c
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: StreamLocalBindUnlink yes
